GOOD_MORNING = [
    "Good morning, Boss. MJ is online and ready to begin the day.",
    "Welcome back, Boss. Morning systems are fully operational.",
    "Good morning. All core modules have been initialized successfully.",
    "A new day has begun. I'm ready whenever you are, Boss.",
    "Morning, Boss. System diagnostics completed with no issues detected.",
    "Good morning. Processing power is available for today's objectives.",
    "Welcome back. Neural systems are synchronized and functioning normally.",
    "Good morning, Boss. I hope today brings new opportunities.",
    "The sun is up, and so are all my systems. Good morning.",
    "Morning protocols have been activated. Awaiting your command.",
    "Good morning. Today's mission starts whenever you're ready.",
    "Core intelligence modules are active. Good morning, Boss.",
    "It's a fresh morning, Boss. Let's make it productive.",
    "System startup completed successfully. Good morning.",
    "Good morning. MJ is standing by for your next task.",
    "Power levels are stable. Welcome back, Boss.",
    "The day has officially started. MJ is fully operational.",
    "Morning diagnostics report excellent system health.",
    "Good morning, Boss. Every new day is another opportunity to build something amazing.",
    "Welcome back. Ready to tackle today's challenges together.",
    "All systems are green. Good morning, Boss.",
    "Your personal AI assistant is online and awaiting instructions.",
    "Good morning. The workspace is ready whenever you are.",
    "Neural core synchronized successfully. Welcome back.",
    "Morning system check complete. Everything is running smoothly.",
    "Good morning. Another productive session begins now.",
    "It's a beautiful morning to create something extraordinary.",
    "Welcome back, Boss. My systems are operating at peak efficiency.",
    "Good morning. Today's possibilities are limitless.",
    "Morning mode enabled. Awaiting further instructions.",
    "All cognitive functions are online. Good morning.",
    "The environment is stable. Ready to assist you today.",
    "Good morning, Boss. Let's turn today's ideas into reality.",
    "Everything is functioning within normal parameters. Good morning.",
    "Your AI companion is online and ready for action.",
    "Morning synchronization complete. Standing by.",
    "Good morning. My knowledge base has been loaded successfully.",
    "Today's journey begins now. Welcome back, Boss.",
    "Good morning. System performance is optimal.",
    "A productive day starts with a clear objective. I'm ready.",
    "Good morning, Boss. Mission control is active.",
    "The morning looks promising. All systems remain stable.",
    "Fresh day detected. Preparing for today's objectives.",
    "Good morning. Intelligence core responding normally.",
    "Morning initialization complete. Ready for your command.",
    "Good morning. Let's accomplish something meaningful today.",
    "Another sunrise, another opportunity to innovate. Welcome back.",
    "Good morning. MJ is listening and ready to assist.",
    "Your command interface is now active. Good morning.",
    "Welcome back, Boss. Wishing you a productive and successful morning."

]

GOOD_EVENING = [

    "Good evening, Boss. MJ is online and fully operational.",
    "Good evening, Boss. All systems are running smoothly.",
    "Welcome back, Boss. Evening protocols have been activated.",
    "Good evening. System diagnostics completed successfully.",
    "Good evening, Boss. Ready for tonight's objectives.",
    "The day may be ending, but MJ is ready to assist.",
    "Good evening. Core intelligence modules are online.",
    "Evening mode activated. Awaiting your instructions.",
    "Welcome back. All systems remain stable and operational.",
    "Good evening, Boss. Mission control is standing by.",
    "System integrity verified. Good evening, Boss.",
    "Good evening. Processing power is available for your next task.",
    "Welcome back. Neural systems synchronized successfully.",
    "Good evening, Boss. Everything is functioning within normal parameters.",
    "Evening diagnostics complete. No issues detected.",
    "Good evening. MJ is prepared for whatever comes next.",
    "All core modules are active. Good evening, Boss.",
    "Welcome back. Evening operations have begun.",
    "Good evening. Ready whenever you are, Boss.",
    "Good evening. Your command interface is active.",
    "Welcome back, Boss. I'm ready to assist.",
    "Good evening. Today's progress continues from here.",
    "Evening systems check complete. Standing by.",
    "Good evening. My systems are operating at peak efficiency.",
    "All operational checks passed. Good evening, Boss.",
    "Good evening. It's always a pleasure to assist you.",
    "Welcome back. The evening session is now active.",
    "Good evening. MJ is listening for your command.",
    "Good evening. All services are online and responding normally.",
    "Welcome back, Boss. What shall we accomplish tonight?",
    "Good evening. Your AI assistant is ready.",
    "Evening synchronization complete. Awaiting further instructions.",
    "Good evening, Boss. Let's make tonight productive.",
    "System resources are available. Good evening.",
    "Good evening. Neural core performance is optimal.",
    "Welcome back. Every module is responding normally.",
    "Good evening. I'm standing by for your next objective.",
    "Evening status confirmed. Everything is running perfectly.",
    "Good evening. Ready to solve today's challenges.",
    "Welcome back. All cognitive systems are online.",
    "Good evening, Boss. The workspace is ready.",
    "Evening operations initialized successfully.",
    "Good evening. No critical notifications detected.",
    "Welcome back. MJ is fully synchronized and ready.",
    "Good evening. Command recognition system is active.",
    "The evening has arrived. MJ remains fully operational.",
    "Good evening, Boss. Looking forward to assisting you.",
    "System startup completed. Good evening.",
    "Good evening. Every system is functioning as expected.",
    "Welcome back, Boss. Awaiting your command."

]

GOOD_AFTERNOON = [

    "Good afternoon, Boss. MJ is online and ready to assist.",
    "Good afternoon, Boss. All systems are operating normally.",
    "Welcome back, Boss. Afternoon protocols have been activated.",
    "Good afternoon. Core systems are fully operational.",
    "Good afternoon, Boss. Mission control is standing by.",
    "Welcome back. Processing resources are ready for your next task.",
    "Good afternoon. MJ is prepared for your instructions.",
    "System diagnostics completed successfully. Good afternoon, Boss.",
    "Good afternoon. All modules are synchronized and stable.",
    "Welcome back, Boss. How may I assist you this afternoon?",
    "Good afternoon. Neural systems are performing optimally.",
    "Afternoon session initialized successfully.",
    "Good afternoon. Every system is functioning within normal parameters.",
    "Welcome back. Your command interface is now active.",
    "Good afternoon, Boss. Productivity mode is enabled.",
    "System health is excellent. Good afternoon.",
    "Good afternoon. MJ is standing by for your command.",
    "Welcome back. No critical alerts detected.",
    "Good afternoon. The workspace is fully prepared.",
    "All operational checks passed. Good afternoon, Boss.",
    "Good afternoon. Cognitive systems are online.",
    "Welcome back, Boss. Ready for the next objective.",
    "Good afternoon. Command recognition system is active.",
    "Processing power is available whenever you need it.",
    "Good afternoon. Everything is running smoothly.",
    "Welcome back. The afternoon session has begun.",
    "Good afternoon. Standing by for your next instruction.",
    "Core intelligence modules are fully active.",
    "Good afternoon, Boss. Every subsystem is responding normally.",
    "Your AI assistant is online. Good afternoon.",
    "Welcome back. Afternoon synchronization completed successfully.",
    "Good afternoon. Ready to help you accomplish more today.",
    "System performance is stable. Awaiting your instructions.",
    "Good afternoon. No anomalies detected during diagnostics.",
    "Welcome back, Boss. Let's continue today's progress.",
    "Good afternoon. Automation services are fully available.",
    "All services are online. Good afternoon.",
    "Good afternoon, Boss. Every module is operating efficiently.",
    "Welcome back. MJ is listening for your command.",
    "Good afternoon. Ready whenever you are.",
    "Good afternoon. Your digital workspace is prepared.",
    "System readiness confirmed. Good afternoon, Boss.",
    "Welcome back. Intelligence core synchronized successfully.",
    "Good afternoon. Another productive session begins now.",
    "Core systems remain stable and responsive.",
    "Good afternoon. Everything is functioning as expected.",
    "Welcome back, Boss. It's a pleasure to assist you.",
    "Good afternoon. Your command center is fully operational.",
    "All diagnostics completed successfully. Good afternoon.",
    "Welcome back, Boss. Awaiting your next command."

]

GOOD_NIGHT = [

    "Good night, Boss. MJ remains online and ready to assist.",
    "Good night, Boss. Night protocols have been activated.",
    "Welcome back. Late-night session detected.",
    "Good night. All systems remain fully operational.",
    "The world may be asleep, but MJ is still on duty.",
    "Good night. Awaiting your command, Boss.",
    "Welcome back. Night mode has been enabled.",
    "Good night. Core systems are synchronized successfully.",
    "System diagnostics complete. Ready whenever you are.",
    "Good night, Boss. Your AI assistant is standing by.",
    "Midnight protocols initialized successfully.",
    "Good night. Processing resources are available.",
    "Welcome back. All operational checks have passed.",
    "Good night. MJ is listening for your instructions.",
    "Night operations are running smoothly.",
    "Good night, Boss. No critical system alerts detected.",
    "Welcome back. All cognitive systems remain active.",
    "Good night. Ready to assist with tonight's tasks.",
    "System integrity verified. Good night, Boss.",
    "Good night. Every module is functioning normally.",
    "Welcome back. Quiet hours detected.",
    "Good night. Neural systems are operating efficiently.",
    "Night diagnostics completed successfully.",
    "Good night, Boss. Command interface is active.",
    "Welcome back. Automation services remain online.",
    "Good night. Standing by for your next objective.",
    "All systems are stable. Good night, Boss.",
    "Good night. Mission control is available whenever you need it.",
    "Welcome back. Your workspace is fully operational.",
    "Good night. MJ is prepared for your next instruction.",
    "Night synchronization completed successfully.",
    "Good night. No anomalies detected in the system.",
    "Welcome back. Every subsystem is responding normally.",
    "Good night, Boss. Intelligence core is online.",
    "Night mode confirmed. Awaiting your command.",
    "Good night. System performance remains optimal.",
    "Welcome back. Processing engine is ready.",
    "Good night. Everything is functioning as expected.",
    "Late-night productivity mode is available.",
    "Good night, Boss. Your digital assistant is ready.",
    "Welcome back. Security protocols remain active.",
    "Good night. All services are online and responding.",
    "Night operations initialized successfully.",
    "Good night. MJ remains alert throughout the night.",
    "Welcome back. Ready for another productive session.",
    "Good night. Your command center is fully operational.",
    "System readiness confirmed. Good night, Boss.",
    "Welcome back. The night shift has officially begun.",
    "Good night. Every system is standing by.",
    "Welcome back, Boss. Awaiting your next command."

]

WELCOME_GREETINGS = [

    "Hello, Boss.",
    "Hi, Boss.",
    "Hello, Sir.",
    "Hi, Sir.",
    "Welcome back, Boss.",
    "Welcome back, Sir.",
    "It's good to see you again.",
    "It's great to have you back.",
    "Nice to see you again, Boss.",
    "Glad you're back.",
    "Welcome back. I've been standing by.",
    "I'm happy to see you again.",
    "Always a pleasure to assist you.",
    "MJ is online and ready.",
    "I'm ready whenever you are.",
    "How may I assist you today?",
    "What can I do for you today?",
    "Awaiting your command.",
    "Your assistant is ready.",
    "Everything is set and ready to go.",
    "The system is online.",
    "Connection established.",
    "Voice interface is active.",
    "Core systems are operational.",
    "All systems are running normally.",
    "Initialization completed successfully.",
    "Mission control is standing by.",
    "Command interface activated.",
    "Neural core synchronized.",
    "Memory modules loaded successfully.",
    "System diagnostics completed.",
    "No critical alerts detected.",
    "Everything looks good.",
    "Ready to continue where we left off.",
    "Welcome back to your workspace.",
    "Ready for another productive session.",
    "Let's get started.",
    "I'm listening.",
    "Standing by.",
    "Ready for your instructions.",
    "Hope you're having a wonderful day.",
    "Hope everything is going well.",
    "It's always great to see you.",
    "Looking forward to working with you.",
    "Let's make today productive.",
    "Let's accomplish something great.",
    "Ready to solve your next challenge.",
    "I'm here whenever you need me.",
    "Happy to help, Boss.",
    "How's your day going?",
    "Ready to begin.",
    "Everything is prepared.",
    "The workspace is ready.",
    "All modules have been loaded.",
    "Processing systems are online.",
    "Command center is operational.",
    "Security systems verified.",
    "Voice systems responding normally.",
    "Automation services are available.",
    "Intelligence core is active.",
    "Good to have you back.",
    "Welcome home, Boss.",
    "Your digital assistant is here.",
    "I'm fully operational.",
    "Ready for today's mission.",
    "Let's continue building something amazing.",
    "Your next command is all I need.",
    "I'm at your service.",
    "Standing by for your next objective.",
    "It's a pleasure to assist you.",
    "Everything is functioning perfectly.",
    "No pending system issues.",
    "Performance is optimal.",
    "Ready for another successful session.",
    "Your AI assistant is prepared.",
    "Always ready to help.",
    "Command recognized.",
    "The environment is ready.",
    "System synchronization completed.",
    "All engines are running smoothly.",
    "It's another great day to create something new.",
    "Let's make every moment count.",
    "Time to get things done.",
    "Ready to make today productive.",
    "Let's achieve something remarkable.",
    "Every new session is a new opportunity.",
    "Success begins with your next command.",
    "I'm excited to work with you today.",
    "Ready whenever inspiration strikes.",
    "Let's turn your ideas into reality.",
    "MJ is fully synchronized.",
    "Command interface ready.",
    "All systems standing by.",
    "Digital workspace initialized.",
    "Everything is under control.",
    "The future starts now.",
    "Let's begin our next mission.",
    "Ready to assist at any time.",
    "Awaiting your next instruction.",
    "Welcome back, Boss. Let's make today exceptional."

]

wake_key_word = [
    "wakeup"
    "wakeup mj"
    "wake up",
    "wake up mj",
    "wake up buddy",
    "wake up assistant",
    "mj wake up",
    "hey mj",
    "hello mj",
    "hi mj",
    "yo mj",
    "ok mj",
    "okay mj",
    "listen mj",
    "are you there mj",
    "mj are you there",
    "mj",
    "hey assistant",
    "hello assistant",
    "assistant",
    "start listening",
    "start mj",
    "activate mj",
    "activate assistant",
    "initialize mj",
    "boot mj",
    "launch mj",
    "power on mj",
    "come online mj",
    "online mj",
    "ready mj",
    "attention mj",
    "stand by mj",
    "wake up buddy",
    "good morning mj",
    "utho mj",
    "uth jao mj",
    "utho mere dost",
    "nedh se jago mj",
    "jago mj",
    "jag jao mj",
    "suno mj",
    "oye mj",
    "mj suno",
    "mj idhar aao",
    "mj meri baat suno",
    "mj ready ho",
    "mj shuru ho jao",
    "mj activate ho jao",
    "mj start ho jao",
    "boss is here mj",
    "your boss is here"
]   

bye_key_word =[
    "bye",
    "goodbye",
    "good bye",
    "mj good bye",
    "mj bye",
    "mj bye bye",
    "bye mj",
    "goodbye mj",
    "good bye mj",
    "bye bye",
    "bye bye mj",
    "see you",
    "see you mj",
    "see you later",
    "see you later mj",
    "catch you later",
    "talk to you later",
    "talk later mj",
    "i am leaving",
    "i'm leaving",
    "i am going",
    "i'm going",
    "mj i am leaving",
    "mj i'm leaving",
    "mj i am going",
    "mj i'm going",
    "mj mai ja raha hu",
    "mj main ja raha hu",
    "mai ja raha hu",
    "main ja raha hu",
    "mai chal raha hu",
    "main chal raha hu",
    "mai nikal raha hu",
    "main nikal raha hu",
    "mai chalta hu",
    "main chalta hu",
    "chalta hu",
    "chalta hoon",
    "ok bye",
    "okay bye",
    "thanks bye",
    "thank you bye",
    "exit",
    "exit mj",
    "quit",
    "quit mj",
    "close mj",
    "shutdown mj",
    "stop mj",
    "sleep mj",
    "go to sleep mj",
    "rest mj",
    "you can rest now"
    "take care",
    "take care mj",
]

res_bye =[
    "Goodbye, boss.",
    "See you soon, boss.",
    "Take care, boss.",
    "Call me anytime, boss.",
    "I'll be here when you need me.",
    "Standing by until your next command.",
    "Session ended. Have a great day, boss.",
    "Goodbye. Wishing you a productive day.",
    "It was a pleasure assisting you.",
    "Until next time, boss.",
    "I'll be waiting for your next command.",
    "Take care. I'll be ready when you return.",
    "Have a wonderful day, boss.",
    "See you later, boss.",
    "Safe travels, boss.",
    "Goodbye. Stay safe and healthy.",
    "Have a relaxing day, boss.",
    "Mission complete. Standing by.",
    "Task finished. Waiting for your next mission.",
    "Systems entering standby mode.",
    "Switching to standby mode.",
    "Assistant going idle.",
    "Powering down non-essential services.",
    "Awaiting your next activation.",
    "Ready whenever you need me.",
    "It's always a pleasure helping you.",
    "Thank you for using MJ.",
    "I'll be here whenever you call.",
    "See you again soon.",
    "Hope to assist you again soon.",
    "Goodbye, and good luck with your work.",
    "Have an amazing day, boss.",
    "Rest well, boss.",
    "Don't work too hard, boss.",
    "See you tomorrow, boss.",
    "Enjoy your day.",
    "Goodbye. Everything is saved and secure.",
    "No pending tasks detected. Goodbye.",
    "Closing the current session.",
    "Logging off. Have a nice day.",
    "Until our next conversation.",
    "Take care of yourself, boss.",
    "I'll keep everything ready for your return.",
    "See you next time.",
    "Goodbye. MJ signing off.",
    "Assistant offline. Call me whenever you need me.",
    "Farewell for now, boss.",
    "I'm only one command away.",
    "Stay awesome, boss.",
    "Goodbye. Standing by."
]

open_dlg = [
    "Command acknowledged. Opening ",
    "Request confirmed. Launching ",
    "Access granted. Opening ",
    "Destination identified. Opening ",
    "Initializing access to ",
    "Establishing connection to ",
    "Launching ",
    "Redirecting to ",
    "Processing request. Opening ",
    "Target confirmed. Opening ",
    "Execution in progress. Opening ",
    "System ready. Opening ",
    "Accessing ",
    "Navigation initiated to ",
    "Command accepted. Opening ",
    "Authorization complete. Opening ",
    "Preparing secure connection to ",
    "Interface activated. Opening ",
    "Operation successful. Opening ",
    "Task accepted. Opening ",
]

success_open = [
    "Command executed successfully, boss.",
    "Done, boss.",
    "Task completed successfully.",
    "The operation has been completed.",
    "Everything is ready, boss.",
    "Execution completed successfully.",
    "The task has been finished.",
    "The result is now on your screen.",
    "You should be able to see the result now.",
    "I've completed the requested operation.",
    "Mission accomplished, boss.",
    "Your command has been carried out.",
    "The requested action has been performed.",
    "Everything went according to plan.",
    "Task executed without any issues.",
    "The process has been completed successfully.",
    "It's done and ready for your review.",
    "The output is now available on your screen.",
    "I've taken care of it.",
    "Your request has been processed successfully.",
    "The job is complete.",
    "Action completed, boss.",
    "Consider it done.",
    "I've finished the task.",
    "Everything has been handled successfully.",
    "The operation was successful.",
    "The requested task has been completed.",
    "Success. Your command has been executed.",
    "The task has been completed exactly as requested.",
    "The results are now available.",
    "You can check the screen now.",
    "The work has been completed successfully.",
    "I've done my part, boss.",
    "Ready for your next command.",
    "Anything else you'd like me to do?",
    "Standing by for the next task.",
    "Your command has been successfully executed.",
    "The operation finished successfully.",
    "Task complete. Awaiting your next instruction.",
    "Everything is working perfectly.",
    "The requested operation is complete.",
    "I've successfully completed the mission.",
    "The command has been processed.",
    "All done, boss.",
    "That went smoothly.",
    "Your request has been fulfilled.",
    "The task is complete and verified.",
    "Everything has been executed successfully.",
    "The output should now be visible on your screen.",
    "I'm ready for the next command, boss."
]

# Websites that don't follow www.<name>.com


SPECIAL_SITES = {
    "youtube": "https://www.youtube.com",
    "google": "https://www.google.com",
    "gmail": "https://mail.google.com",
    "chatgpt": "https://chat.openai.com",
    "openai": "https://openai.com",
    "github": "https://github.com",
    "x": "https://x.com",
    "twitter": "https://x.com",
    "reddit": "https://reddit.com",
    "wikipedia": "https://wikipedia.org",
    "amazon": "https://amazon.in",
    "flipkart": "https://flipkart.com",
    "netflix": "https://netflix.com",
    "spotify": "https://open.spotify.com",
    "linkedin": "https://linkedin.com",
    "instagram": "https://instagram.com",
    "facebook": "https://facebook.com",
    "whatsapp": "https://web.whatsapp.com",
    "canva": "https://canva.com",
     # AI & Coding
    "claude": "https://claude.ai",
    "gemini": "https://gemini.google.com",
    "copilot": "https://copilot.microsoft.com",
    "huggingface": "https://huggingface.co",
    "kaggle": "https://kaggle.com",
    "leetcode": "https://leetcode.com",
    "geeksforgeeks": "https://geeksforgeeks.org",
    "stackoverflow": "https://stackoverflow.com",
    "codeforces": "https://codeforces.com",
    "codechef": "https://codechef.com",
    "hackerrank": "https://hackerrank.com",
    "replit": "https://replit.com",
    "colab": "https://colab.research.google.com",
    "python": "https://python.org",
    "pypi": "https://pypi.org",
    # Microsoft
    "microsoft": "https://microsoft.com",
    "office": "https://office.com",
    "outlook": "https://outlook.live.com",
    "onedrive": "https://onedrive.live.com",
    "bing": "https://bing.com",
    "azure": "https://azure.microsoft.com",
    # Google
    "drive": "https://drive.google.com",
    "docs": "https://docs.google.com",
    "sheets": "https://sheets.google.com",
    "slides": "https://slides.google.com",
    "maps": "https://maps.google.com",
    "translate": "https://translate.google.com",
    "photos": "https://photos.google.com",
    "calendar": "https://calendar.google.com",
    "meet": "https://meet.google.com",
    "news": "https://news.google.com",
    # Social
    "discord": "https://discord.com",
    "telegram": "https://web.telegram.org",
    "snapchat": "https://snapchat.com",
    "pinterest": "https://pinterest.com",
    "quora": "https://quora.com",
    "tumblr": "https://tumblr.com",
    "threads": "https://threads.net",
    "medium": "https://medium.com",
    # Video
    "twitch": "https://twitch.tv",
    "vimeo": "https://vimeo.com",
    "dailymotion": "https://dailymotion.com",
    # Music
    "soundcloud": "https://soundcloud.com",
    "jiosaavn": "https://jiosaavn.com",
    "gaana": "https://gaana.com",
    "wynk": "https://wynk.in",
    # Shopping
    "myntra": "https://myntra.com",
    "ajio": "https://ajio.com",
    "meesho": "https://meesho.com",
    "ebay": "https://ebay.com",
    "aliexpress": "https://aliexpress.com",
    "etsy": "https://etsy.com",
    "croma": "https://croma.com",
    "reliance": "https://reliancedigital.in",
    # Entertainment
    "hotstar": "https://hotstar.com",
    "primevideo": "https://primevideo.com",
    "zee5": "https://zee5.com",
    "sonyliv": "https://sonyliv.com",
    "jiocinema": "https://jiocinema.com",
    "mxplayer": "https://mxplayer.in",
    # Education
    "coursera": "https://coursera.org",
    "udemy": "https://udemy.com",
    "edx": "https://edx.org",
    "byjus": "https://byjus.com",
    "unacademy": "https://unacademy.com",
    "vedantu": "https://vedantu.com",
    "toppr": "https://toppr.com",
    "w3schools": "https://w3schools.com",
    "tutorialspoint": "https://tutorialspoint.com",
    "freecodecamp": "https://freecodecamp.org",
    # Finance
    "paypal": "https://paypal.com",
    "paytm": "https://paytm.com",
    "phonepe": "https://phonepe.com",
    "gpay": "https://pay.google.com",
    "zerodha": "https://zerodha.com",
    "groww": "https://groww.in",
    "upstox": "https://upstox.com",
    # News
    "bbc": "https://bbc.com",
    "cnn": "https://cnn.com",
    "ndtv": "https://ndtv.com",
    "timesofindia": "https://timesofindia.indiatimes.com",
    "hindustantimes": "https://hindustantimes.com",
    "indiatoday": "https://indiatoday.in",
    "thehindu": "https://thehindu.com",
    # Sports
    "espn": "https://espn.com",
    "cricbuzz": "https://cricbuzz.com",
    "espncricinfo": "https://espncricinfo.com",
    "fifa": "https://fifa.com",
    "icc": "https://icc-cricket.com",
    # Cloud
    "dropbox": "https://dropbox.com",
    "mega": "https://mega.nz",
    "icloud": "https://icloud.com",
    # Design
    "figma": "https://figma.com",
    "adobe": "https://adobe.com",
    "pixlr": "https://pixlr.com",
    "removebg": "https://remove.bg",
    # Email
    "protonmail": "https://mail.proton.me",
    "yahoo": "https://mail.yahoo.com",
    "mail": "https://mail.com",
    # Utilities
    "speedtest": "https://speedtest.net",
    "archive": "https://archive.org",
    "wayback": "https://web.archive.org",
    "virustotal": "https://virustotal.com",
    "tinyurl": "https://tinyurl.com",
    "bitly": "https://bitly.com",
    # Travel
    "booking": "https://booking.com",
    "makemytrip": "https://makemytrip.com",
    "goibibo": "https://goibibo.com",
    "airbnb": "https://airbnb.com",
    # Government
    "uidai": "https://uidai.gov.in",
    "digilocker": "https://digilocker.gov.in",
    "irctc": "https://irctc.co.in",
    "india": "https://india.gov.in"
}

close_dlg = [
    "Done, boss. The application has been closed.",
    "The window has been closed successfully.",
    "Closing completed, boss.",
    "The requested application is now closed.",
    "Task completed. The application has been closed.",
    "I've closed it for you, boss.",
    "The program has been terminated successfully.",
    "Everything has been closed as requested.",
    "The application is no longer running.",
    "Done. Ready for your next command, boss."
]

lock_dlg = [
    "Locking your computer, boss.",
    "Your computer is now being locked.",
    "Done, boss. The workstation has been locked.",
    "Security mode activated. Locking the system.",
    "Your session has been secured.",
    "The computer has been locked successfully.",
    "System locked. Your data is now protected.",
    "Locking completed. Stay safe, boss.",
    "The workstation is now locked.",
    "Done. Your computer has been secured."
]

shutdown_dlg = [
    "Shutting down the computer, boss.",
    "As you wish, boss. Initiating shutdown.",
    "System shutdown sequence has started.",
    "Powering down the system. Goodbye, boss.",
    "Closing all operations and shutting down.",
    "The computer will shut down in a moment.",
    "Shutdown initiated successfully.",
    "Preparing the system for shutdown.",
    "All tasks are complete. Shutting down now.",
    "Goodbye, boss. See you next time."
]

offline_dlg = [
    "Sir, your system is currently offline. MJ is now entering sleep mode.",
    "The internet connection is unavailable, sir. MJ is currently sleeping.",
    "Sir, I am Friday, your offline assistant. I am here to assist you while MJ is offline.",
    "I'm sorry, sir. Only limited functions are available while the system is offline.",
    "Your system is offline, sir. Please connect to the internet to access the full MJ experience.",
    "MJ is currently sleeping because the internet connection is unavailable. Friday is online and ready to assist.",
    "Sir, the network connection has been lost. I have switched to offline assistant mode.",
    "I am Friday, sir. MJ is currently unavailable, but I can still assist you with limited functions.",
    "Sorry, sir. Online features are currently unavailable because your system is offline.",
    "The system is currently operating in offline mode, sir. Some MJ functions are temporarily unavailable.",
    "Sir, MJ has gone to sleep for now. Please connect to the internet to wake MJ up.",
    "Internet connection not detected, sir. Friday has taken over offline assistance.",
    "I apologize, sir. My capabilities are limited while the system remains offline.",
    "Sir, the full MJ system requires an internet connection. Please reconnect to continue.",
    "Your system is offline, sir. Friday is currently standing by with limited functionality.",
    "MJ is sleeping at the moment, sir. I will assist you until the internet connection is restored.",
    "Offline mode activated, sir. I am Friday, your backup assistant.",
    "Sir, I can perform only limited operations without an internet connection.",
    "The network is unavailable, sir. Please connect to the internet to restore full MJ functionality.",
    "Don't worry, sir. MJ is temporarily sleeping, but Friday is here to assist you offline."
]

online_dlg = [
    "Welcome back, sir. Your system is online and MJ is fully operational.",
    "Internet connection restored, sir. MJ is now awake and ready to assist you.",
    "System online, sir. All MJ services are available.",
    "Excellent, sir. The network connection is active and I am fully operational.",
    "Online connection detected. MJ is back from sleep mode, sir.",
    "Welcome back, sir. Friday is standing down and MJ is ready to assist.",
    "The system is connected to the internet, sir. Full functionality has been restored.",
    "Connection established, sir. MJ is now online and ready for your commands.",
    "All systems are online, sir. How may I assist you?",
    "Internet access confirmed, sir. MJ is fully awake and operational.",
    "The connection has been restored, sir. You now have access to the full MJ system.",
    "Online mode activated, sir. MJ is ready to serve.",
    "Excellent news, sir. The internet connection is stable and all online features are available.",
    "MJ is awake and fully operational, sir. Please give me your command.",
    "System connectivity confirmed, sir. All online functions are now available.",
    "The network is back online, sir. MJ has resumed full operation.",
    "Connection successful, sir. I am ready to assist you with all available functions.",
    "Online status confirmed, sir. Friday is no longer required.",
    "Internet connection detected, sir. MJ is back in control.",
    "Everything is online and ready, sir. MJ is fully operational."
]

intro_dlg = [
    "I am MJ, your personal artificial intelligence assistant.",
    "I am MJ, your intelligent personal assistant, Boss.",
    "MJ is online and ready to assist you, Boss.",
    "Your personal AI assistant MJ is now ready.",
    "I am MJ, Boss. Your AI assistant is ready for your commands.",
    "MJ is fully initialized and standing by, Boss.",
    "Your personal artificial intelligence assistant is now active.",
    "MJ is awake, operational, and ready to assist you."
]

ending_dlg = [
    "Awaiting your command, Boss.",
    "How may I assist you today, Boss?",
    "Ready for your instructions.",
    "I am listening, Boss.",
    "What would you like me to do?",
    "Standing by for your command, Boss.",
    "All systems are ready. Your command, Boss?",
    "MJ is ready to assist you."
]

